### ISSUE TITLE
gitlab 11.9.10 tag & subgit 3.3.6

### ISSUE THREAD

**Issue by csonuryilmaz** [cmarquardt/docker-gitlab-ee-subgit#2]
Hi again, :blush:  (#1) 
I've upgraded our gitlab instance using **11.9.8-ee.0** tag. We used it without any problem up to now. Today a [security update](https://about.gitlab.com/2019/04/29/security-release-gitlab-11-dot-10-dot-2-released/) is announced. (**11.9.10**) This update fixes several significant vulnerabilities and we want to upgrade to that version. 

Also there is an [11.9.9](https://about.gitlab.com/2019/04/24/gitlab-11-5-11-released/) update which I couldn't find at [tags tab](https://hub.docker.com/r/marq/gitlab-ee-subgit/tags) on docker hub. It was released on 24th April.
1. Will **11.9.10-ee.0** tag be relased on docker hub?
2. If won't, how can I upgrade to **11.9.10-ee.0** tag by myself? 
*Maybe editing my own docker file?*

**TMate** released a new version of `Subgit`. [3.3.6](https://subgit.com/documentation/release-notes.html) I think it's time to upgrade version of `Subgit` in docker file, if there won't be any problem.

**Comment by cmarquardt** [comment]
Hi again!

Thanks for making me aware - as you know I'm not watching the Gitlab and SubGit releases very closely any more, so I'm really grateful!

I started to build the missing images but it will need a few hours before they become available (and only if I didn't make a mistake). 11.9.9 and 11.9.10 should follow tomorrow, and both will contain the new SubGit. So will all other future updates of the images, starting with 11.10.2. I'll keep you posted...

**Comment by csonuryilmaz** [comment]
Thanks a lot, for quick response and action! It seems to be ready. 

Now [tags](https://hub.docker.com/r/marq/gitlab-ee-subgit/tags) and [builds](https://hub.docker.com/r/marq/gitlab-ee-subgit/builds) tabs have **11.9.10-ee.0**. Also [docker file](https://github.com/cmarquardt/docker-gitlab-ee-subgit/blob/06ba67bd18752f689210891004a56232d09c8876/Dockerfile) has `SUBGIT_VERSION 3.3.6`. :tada:

**Comment by cmarquardt** [comment]
Yes, that's right - could you give them a try a let me know if they work for you?

Many thanks!

**Comment by csonuryilmaz** [comment]
I'm starting to work in a short time and I'll share results as soon as possible.

**Comment by csonuryilmaz** [comment]
I've upgraded without any problem. Container is up and running healthy:

![gitlab-container](https://user-images.githubusercontent.com/7355362/56988511-e6a0a700-6b98-11e9-927b-bb1bbd5acd34.png)

Also, `subgit` is installed successfully:
```bash
root@gitlab:/# subgit --version
SubGit version 3.3.6 ('Bobique') build #4276
  (c) TMate Software 2012-2018 (http://subgit.com/)
root@gitlab:/# 
```

Thanks a lot, for the new tagged versions. :relaxed:

**Comment by cmarquardt** [comment]
Great to hear it works! And thanks again for pinging me for the missing versions and updates;-)
